package ru.geekbrains.librariescoursepractice.presenter

import ru.geekbrains.librariescoursepractice.presenter.IListPresenter
import ru.geekbrains.librariescoursepractice.view.IUserItemView

interface IUserListPresenter : IListPresenter<IUserItemView>